# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=11, verbose_name='收件人名')),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('postcode', models.CharField(max_length=7, verbose_name='邮编')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
