import re

print(re.findall("ab", "abcdefabcd"))
print(re.findall("中国", "你好，中国"))
print(re.findall("ab|ef", "abcdefabcd"))
print(re.findall("ab|bc", "abcdefabcd"))
print(re.findall("张.丰", "张三丰，张四丰，张五丰"))
print(re.findall("张..", "张三丰，张四丰，张五丰"))
print(re.findall("[abcd]", "abcdefabcd"))
print(re.findall("[a-z]", "How are you"))
print(re.findall("[h0-9]", "h007"))
print(re.findall("[^h0-9]", "h 0 0 7"))
print(re.findall("[^ ]", "h 0 0 7"))
print(re.findall("^James", "Hi, James!"))
print(re.findall("James$", "Hi, James!"))
print(re.findall("^James$", "James"))
print(re.findall("[0-9]+", "今天是2020年2月19日"))
print(re.findall("[A-Z][a-z]*", "Hi, James. How are you?"))
print(re.findall("-?[0-9]+", "1 -2 3 -4 5 -6"))
print(re.findall("1[0-9]{10}", "13368226964"))
print(re.findall("[1-9][0-9]{4,10}", "2379773801"))
print(re.findall("\d{1,5}", "PORT=11111, http:12"))
print(re.findall("\D+", "PORT=11111, http:12"))
print(re.findall("\w+", "PORT=11111, http:12"))
print(re.findall("\W+", "PORT=11111, http:12"))
print(re.findall("\w+\s+\w+", "hello      world"))
print(re.findall("\S+", "hellosdnlejnwmedeks,jwdduhqwqwxneuwdoi"))
print(re.findall(r"\bis", "This is a test"))
print(re.findall("\Bis", "This is a test"))
print(re.findall(r"\b[A-Z]+[a-z]*", "Hello iPython"))
