# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('callback_url', models.URLField(verbose_name='url地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='股票编码')),
                ('company_name', models.CharField(max_length=64, verbose_name='公司名称')),
                ('area', models.CharField(max_length=30, verbose_name='所属区域')),
                ('update', models.DateField(verbose_name='上市日期')),
                ('concepts', models.CharField(max_length=200, verbose_name='涉及概念')),
                ('main_business', models.CharField(max_length=200, verbose_name='主营业务')),
                ('per_net_asset', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股净资产')),
                ('per_profit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股收益')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='净利润')),
                ('net_profit_growth_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='净利润增长率')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='营业收入')),
                ('per_net_cash_flow', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股现金流')),
                ('per_net_fund', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股公积金')),
                ('per_net_unprofit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股未分配利润')),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总股本')),
                ('flow_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='流通股')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'ordering': ['-id'],
                'db_table': 'Stock',
            },
        ),
    ]
