# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180930_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='number',
            new_name='stonumber',
        ),
    ]
