# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20180930_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stonumber',
            field=models.CharField(max_length=20, verbose_name='股票编码'),
        ),
    ]
