# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20181012_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='esp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股收益'),
        ),
    ]
