# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-17 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='order_order_goods',
        ),
    ]
