# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='charpwd',
            field=models.IntegerField(default=0, verbose_name='交易密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='frozen_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='冻结资金'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总资金'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='持有数量'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='frozen',
            field=models.IntegerField(blank=True, null=True, verbose_name='冻结股'),
        ),
    ]
