# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20181010_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='charpwd',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tradepwd',
        ),
        migrations.AddField(
            model_name='bank',
            name='tradepwd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交易密码'),
        ),
    ]
