# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20181010_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bankNo',
            field=models.CharField(max_length=40, verbose_name='卡号'),
        ),
    ]
