# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20181010_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='frozen_money',
            new_name='frozenmoney',
        ),
    ]
