# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('logo', models.ImageField(upload_to='brand', verbose_name='Logo图片')),
                ('first_letter', models.CharField(max_length=1, verbose_name='品牌首字母')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='SaleAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='销售属性值名称')),
            ],
            options={
                'verbose_name': '销售属性值',
                'verbose_name_plural': '销售属性值',
                'db_table': 'goods_sale_attr_value',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='SKU名称')),
                ('caption', models.CharField(max_length=100, verbose_name='副标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('comments', models.IntegerField(default=0, verbose_name='评价数')),
                ('is_launched', models.BooleanField(default=True, verbose_name='是否上架销售')),
                ('default_image_url', models.ImageField(default=None, upload_to='sku', verbose_name='默认图片')),
                ('version', models.IntegerField(default=0, verbose_name='库存版本')),
                ('sale_attr_value', models.ManyToManyField(to='goods.SaleAttrValue')),
            ],
            options={
                'verbose_name': 'SKU表',
                'verbose_name_plural': 'SKU表',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='sku_images', verbose_name='图片路径')),
                ('sku',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='sku')),
            ],
            options={
                'verbose_name': 'SKU图片',
                'verbose_name_plural': 'SKU图片',
                'db_table': 'goods_sku_image',
            },
        ),
        migrations.CreateModel(
            name='SKUSpecValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='SKU规格名称值')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU')),
            ],
            options={
                'verbose_name': 'SKU规格属性值表',
                'verbose_name_plural': 'SKU规格属性值表',
                'db_table': 'goods_spu_spec_value',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('comments', models.IntegerField(default=0, verbose_name='评价数量')),
                ('brand',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Brand', verbose_name='品牌')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Catalog',
                                              verbose_name='商品类别')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
            },
        ),
        migrations.CreateModel(
            name='SPUSaleAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='SPU属性名称')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPU')),
            ],
            options={
                'verbose_name': 'SPU销售属性',
                'verbose_name_plural': 'SPU销售属性',
                'db_table': 'goods_spu_sale_attr',
            },
        ),
        migrations.CreateModel(
            name='SPUSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='SPU规格名称')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPU')),
            ],
            options={
                'verbose_name': 'SPU规格',
                'verbose_name_plural': 'SPU规格',
                'db_table': 'goods_spu_spec',
            },
        ),
        migrations.AddField(
            model_name='skuspecvalue',
            name='spu_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPUSpec'),
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPU'),
        ),
        migrations.AddField(
            model_name='saleattrvalue',
            name='spu_sale_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPUSaleAttr',
                                    verbose_name='销售属性'),
        ),
    ]
