# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='callback_url',
            field=models.URLField(blank=True, null=True, verbose_name='url地址'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='concepts',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='涉及概念'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='flow_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='流通股'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='main_business',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='主营业务'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='净利润'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='net_profit_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='净利润增长率'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per_net_asset',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股净资产'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per_net_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股现金流'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per_net_fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股公积金'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per_net_unprofit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股未分配利润'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股收益'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总股本'),
        ),
    ]
