# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20180930_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='per_profit',
            new_name='eps',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='per_net_fund',
            new_name='reservedPerShare',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='update',
            new_name='timeToMarket',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='concepts',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='flow_money',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='income',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='main_business',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='net_profit_growth_rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='per_net_asset',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='per_net_cash_flow',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='per_net_unprofit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_money',
        ),
        migrations.AddField(
            model_name='stock',
            name='bvps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='每股净资'),
        ),
        migrations.AddField(
            model_name='stock',
            name='fixedAssets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='固定资产'),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='细分行业'),
        ),
        migrations.AddField(
            model_name='stock',
            name='liquidAssets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='流动资产'),
        ),
        migrations.AddField(
            model_name='stock',
            name='outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='流通股本'),
        ),
        migrations.AddField(
            model_name='stock',
            name='pb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='市净率'),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='市盈率'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='公积金'),
        ),
        migrations.AddField(
            model_name='stock',
            name='totalAssets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总资产(万)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='totals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总股本(万)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='地区'),
        ),
    ]
