# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_bosstock_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealstock',
            name='stock',
            field=models.CharField(max_length=400, verbose_name='股票信息'),
        ),
    ]
